version: "3.9"
services:
  frontend:
    build: ./frontend
    networks:
      - frontend
    volumes:
      - unix_socket_dir:${UNIX_SOCKET_DIR}
      - static:${STATIC_ROOT}
      - media:${MEDIA_ROOT}
      - ./conf/nginx/templates:/etc/nginx/templates:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - UNIX_SOCKET_DIR
      - BACKEND_SOCKET
      - STATIC_ROOT
      - MEDIA_ROOT
      - NGINX_INTERNAL_PORT
      - NGINX_EXTERNAL_PORT
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    depends_on:
      - backend

  backend:
    build: ./backend
    command: [ "/backend/entrypoint.sh" ]
    secrets:
      - db_name
      - db_user
      - db_password
      - django_secret_key
      - redis_password
    networks:
      - backend
    volumes:
      - unix_socket_dir:${UNIX_SOCKET_DIR}
      - static:${STATIC_ROOT}
      - media:${MEDIA_ROOT}
    environment:
      - ALLOWED_HOSTS
      - STATIC_ROOT
      - MEDIA_ROOT
      - PYTHONDONTWRITEBYTECODE
      - PYTHONUNBUFFERED
      - LOGLEVEL
      - UNIX_SOCKET_DIR
      - DB_ENGINE
      - DJANGO_DEFAULT_ADMIN_USERNAME
      - DJANGO_DEFAULT_ADMIN_PASSWORD
      - BACKEND_SOCKET
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "if [ -f '$${UNIX_SOCKET_DIR}/$${BACKEND_SOCKET}' ]" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  database:
    image: postgres:14
    networks:
      - backend
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_name
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "$$(cat /run/secrets/db_name)"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  redis:
    build: ./redis
    command: [ "/redis/entrypoint.sh" ]
    secrets:
      - redis_password
    networks:
      - backend

secrets:
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  redis_password:
    file: ./secrets/redis_password
  django_secret_key:
    file: ./secrets/django_secret_key

networks:
  frontend:
  backend:

volumes:
  unix_socket_dir:
  db_data:
  static:
  media: