openapi: 3.0.3
info:
  title: QVantelShop
  description: QVantel Technical test api
  version: "0.1"
  contact:
    email: dowdyph0@gmail.com
servers:
  - url: /api/
tags:
  - name: auth
    description: Everything related to user authentication
  - name: shop
    description: Everything related to the item shop/store

paths:
  /token/:
    post:
      tags:
        - auth
      summary: Requests a new access token
      description: Requests a new access token
      requestBody:
        description: Requests a new access token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewJWTToken'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTToken'
               
  /token/refresh/:
    post:
      tags:
        - auth
      summary: Requests a new access token
      description: Requests a new access token
      requestBody:
        description: Requests a new access token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshJWTToken'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessJWTToken'

  /items/:
    get:
      tags:
        - shop
      summary: List all the items of the shop
      description: List all the items of the shop
      responses:
        '200':
          description: List all the items of the shop
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemDetail'
  
  /cart/{id}/:
    get:
      tags:
        - shop
      summary: Retrieves the detail of a cart
      description: Retrieves the detail of a cart
      parameters:
        - name: id
          in: path
          description: ID of cart to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CartDetail'
  /cart/{id}/update/:
    post:
      tags:
        - shop
      summary: Updates one item of a cart
      description: Updates one item of a cart
      parameters:
        - name: id
          in: path
          description: ID of cart to return
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Updates one item of a cart
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartAdd'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CartDetail'
  /cart/{id}/add/:
    post:
      tags:
        - shop
      summary: Adds one item to a cart
      description: Adds one item to a cart
      parameters:
        - name: id
          in: path
          description: ID of cart to return
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Adds one item to a cart
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartAdd'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CartDetail'
  /cart/checkout/:
    post:
      tags:
        - shop
      summary: Creates a new cart
      description: Creates a new cart
      requestBody:
        description: Requests a new access token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartCheckOut'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CartID'
  
components:
  schemas:
    NewJWTToken:
      type: object
      properties:
        username:
          type: string
          format: text
          example: user
        password:
          type: string
          format: text
          example: 1234
    
    JWTToken:
      type: object
      properties:
        access:
          type: string
          format: base64
        refresh:
          type: string
          format: base64
    
    RefreshJWTToken:
      type: object
      properties:
        refresh:
          type: string
          format: base64
    
    AccessJWTToken:
      type: object
      properties:
        access:
          type: string
          format: base64
  
    ItemDetail:
      type: object
      properties: 
        id: 
          type: integer
          format: int32
        name: 
          type: string
        price: 
          type: string
        price_currency: 
          type: string
        image_url: 
          type: string
  
    CartAdd:
      type: object
      properties:
        item:
          type: integer
          format: int32

    CartCheckOut:
      type: object
      properties:
        country_code: 
          type: string
        cart_items: 
          type: array
          items: 
            type: object
            properties: 
              item_id: 
                type: integer
                format: int32
              quantity: 
                type: string
    
    CartID:
      type: object
      properties:
        id:
          type: integer
          format: int32
  
    CartDetail:
      type: object
      properties:
        id: 
          type: integer
          format: int32
        user: 
          type: object
          properties: 
            id: 
              type: integer
              format: int32
            username: 
              type: string
            first_name: 
              type: string
            last_name: 
              type: string
        price: 
          type: string
        price_currency: 
          type: string
        country_code: 
          type: string
        country_name: 
          type: string
        cart_items: 
          type: array
          items: 
            type: object
            properties: 
              id: 
                type: integer
                format: int32
              quantity: 
                type: string
              price: 
                type: string
              price_currency: 
                type: string
              item: 
                type: object
                properties: 
                  id: 
                    type: integer
                    format: int32
                  name: 
                    type: string
                  price: 
                    type: string
                  price_currency: 
                    type: string
                  image_url: 
                    type: string